# Generated by Django 4.0.2 on 2022-03-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('stn_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'busStop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_grade', models.TextField(blank=True, db_column='AREA_GRADE', null=True)),
                ('avr_score', models.BigIntegerField(blank=True, db_column='AVR_SCORE', null=True)),
                ('bottom_score', models.BigIntegerField(blank=True, db_column='BOTTOM_SCORE', null=True)),
                ('compet_rate', models.TextField(blank=True, db_column='COMPET_RATE', null=True)),
                ('house_manage_no', models.BigIntegerField(blank=True, db_column='HOUSE_MANAGE_NO', null=True)),
                ('model_no', models.TextField(blank=True, db_column='MODEL_NO', null=True)),
                ('top_score', models.BigIntegerField(blank=True, db_column='TOP_SCORE', null=True)),
                ('total_req', models.TextField(blank=True, db_column='TOTAL_REQ', null=True)),
            ],
            options={
                'db_table': 'competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('address', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('build_comp', models.TextField(blank=True, db_column='BUILD_COMP', null=True)),
                ('house_manage_no', models.BigIntegerField(db_column='HOUSE_MANAGE_NO', primary_key=True, serialize=False)),
                ('house_name', models.TextField(blank=True, db_column='HOUSE_NAME', null=True)),
                ('house_secd', models.TextField(blank=True, db_column='HOUSE_SECD', null=True)),
                ('imprmn_bsns_at', models.TextField(blank=True, db_column='IMPRMN_BSNS_AT', null=True)),
                ('lat', models.TextField(blank=True, db_column='LAT', null=True)),
                ('lot', models.TextField(blank=True, db_column='LOT', null=True)),
                ('lrscl_bldlnd_at', models.TextField(blank=True, db_column='LRSCL_BLDLND_AT', null=True)),
                ('mdat_trget_area_secd', models.TextField(blank=True, db_column='MDAT_TRGET_AREA_SECD', null=True)),
                ('place_code', models.TextField(blank=True, db_column='PLACE_CODE', null=True)),
                ('rent_secd', models.TextField(blank=True, db_column='RENT_SECD', null=True)),
                ('speclt_rdn_earth_at', models.TextField(blank=True, db_column='SPECLT_RDN_EARTH_AT', null=True)),
                ('start_receipt', models.TextField(blank=True, db_column='START_RECEIPT', null=True)),
                ('supply_size', models.BigIntegerField(blank=True, db_column='SUPPLY_SIZE', null=True)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('dutyeryn_code', models.TextField(blank=True, db_column='dutyEryn_code', null=True)),
                ('duty_emcls_code', models.TextField(blank=True, db_column='duty_Emcls_code', null=True)),
                ('duty_code', models.TextField(blank=True, null=True)),
                ('hname', models.TextField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('house_manage_no', models.BigIntegerField(db_column='HOUSE_MANAGE_NO', primary_key=True, serialize=False)),
                ('school', models.TextField(blank=True, null=True)),
                ('subway', models.TextField(blank=True, null=True)),
                ('mart', models.TextField(blank=True, null=True)),
                ('park', models.TextField(blank=True, null=True)),
                ('hospital', models.TextField(blank=True, null=True)),
                ('busstop', models.TextField(blank=True, db_column='busStop', null=True)),
            ],
            options={
                'db_table': 'infra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mart',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('mart_name', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('park_name', models.TextField(blank=True, null=True)),
                ('park_type', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'park',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('school_kind', models.TextField(blank=True, null=True)),
                ('school_name', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoldCostMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_code', models.TextField(blank=True, null=True)),
                ('area_grade', models.TextField(blank=True, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('mean_cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sold_cost_mean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lot', models.FloatField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('route_name', models.TextField(blank=True, null=True)),
                ('stn_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subway',
                'managed': False,
            },
        ),
    ]
