# Generated by Django 4.0.2 on 2022-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_convinient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCode',
            fields=[
                ('place', models.TextField(blank=True, null=True)),
                ('place_code', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'place_code',
                'managed': False,
            },
        ),
    ]
