# Generated by Django 4.0.2 on 2022-03-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convinient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('sname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'convinient',
                'managed': False,
            },
        ),
    ]
